version: "3.8"

services:
  nextjs-app:
    build: .
    container_name: fiorano_nextjs
    restart: always
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:8.0
    container_name: fiorano_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fiorano_api_docs
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
